Update PHP template
gitpod-io/Gitpod-PHP-Debug pull request #1
Opened 2022-01-11 08:22 UTC by pawlean

Open this PR in Gitpod and debug the PHP files

2022-01-11 08:27 UTC, pawlean commented
Do you want to peer review this PR? 🙏🏼

2022-01-11 11:24 UTC, axonasif commented
I just launched a workspace from your fork and it's working as intended 🎉

2022-01-12 11:52 UTC, Cahllagerfeld approved these changes
As Asif said, for me its working as well 👍

2022-01-12 13:26 UTC, axonasif requested changes

2022-01-12 13:26 UTC, axonasif commented on .gitpod.Dockerfile
> +RUN sudo apt-get update && sudo apt-get install php-xdebug -y
I think using `sudo install-packages php-xdebug` would be a better approach since `install-packages` is basically a wrapper around the `apt-get` cli made by the Gitpod folks 🙂

This particular wrapper script takes all the necessary steps for you and installs your specified packages while enforcing non-interactive mode and cleaning out all unnecessary file caches to ensure that the resulted docker image is lightweight in size ☺️

2022-01-12 13:26 UTC, axonasif commented on README.md
> +This is an example of how to debug PHP configured for ephemeral nix based development environments on [Gitpod](https://www.gitpod.io/).
Are you referring to `Unix`/`*nix` by the word `nix` here? I think it can get confusing since there is a thing called Nix or NixOS around 😅

2022-01-12 13:26 UTC, axonasif commented on README.md
> +To get started with nix on Gitpod, copy the contents of this foler to your own project. To learn more, please see the [Getting Started](https://www.gitpod.io/docs/getting-started) documentation.
Now I'm guessing that you used the https://github.com/gitpod-io/template-nix/ as a template readme to workout from, we just need to edit these parts now 🙂

2022-01-12 13:36 UTC, axonasif approved these changes
Looks fine now!

2022-01-12 13:37 UTC, merged